#!/usr/bin/env python3
"""Calculadora inteligênte.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FAFrNFC5UQVxdEY-64xSLvdf_hs8dfH
"""

num1 = float(input('digite o primeiro numero: '))
num2 = float(input('digite o segundo numero: '))
print('Gostaria de ver todos os operadores possíveis ou gostaria de ver algum em específico?')
pergunta = input('Caso queira digite qual: ')
if pergunta == 'todos':
  print('Esses são os possivel valores aritimeticos: ')
  print('Soma: ', num1 + num2)
  print('Subtração: ', num1 - num2)
  print('Multiplicação: ', num1 * num2)
  print('Divisão: ', num1 / num2)
  print('Divisão inteira: ', num1 // num2)
  print('Resto da divisão: ', num1 % num2)
  print('Potência: ', num1 ** num2)
elif pergunta == 'soma':
  print('Soma: ', num1 + num2)
elif pergunta == 'subtração':
  print('Subtração: ', num1 - num2)
elif pergunta == 'multiplicação':
  print('Multiplicação: ', num1 * num2)
elif pergunta == 'divisão':
  print('Divisão: ', num1 / num2)
elif pergunta == 'divisão inteira':
  print('Divisão inteira: ', num1 // num2)
elif pergunta == 'resto da divisão':
  print('Resto da divisão: ', num1 % num2)
elif pergunta == 'potência':
  print('Potência: ', num1 ** num2)
